tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "zsh"
brew "tmux"
brew "git"
brew "tig"
brew "ghq"
brew "vim"
brew "fasd"
brew "fzf"
brew "anyenv"
brew "direnv"
brew "reattach-to-user-namespace"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "gawk"
brew "mysql-client"
brew "jq"
brew "jid"
brew "gron"
brew "tree"
brew "ctop"
tap "beeftornado/rmtree"
brew "brew-rmtree"
brew "lesspipe"
brew "highlight"
brew "source-highlight"
brew "gh"
brew "exa"
brew "bat"
brew "tldr"
brew "ripgrep"
brew "translate-shell"
brew "curl"
brew "mackup"
brew "awscli"
tap "aws/tap"
brew "aws-sam-cli"
tap "fabianishere/personal"
brew "pam_reattach"
brew "gradle-completion"
brew "mycli"
brew "pipx"
tap "hashicorp/tap"
brew "terraform-ls"

cask "font-hackgen"
cask "font-hackgen-nerd"

cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "session-manager-plugin"
cask "iterm2"
cask "docker"
cask "visual-studio-code"
cask "intellij-idea"

cask "appcleaner"
cask "microsoft-edge"
tap "homebrew/cask-versions"
cask "microsoft-edge-beta"
cask "google-japanese-ime"
cask "stack-stack"
cask "dropbox"
cask "tableplus"
cask "postman"
cask "viscosity"
cask "krisp"
cask "cyberduck"
cask "zoom"

cask "keyboardcleantool"
cask "alfred"
cask "bettertouchtool"
cask "karabiner-elements"
cask "showyedge"
cask "fuwari"
cask "bartender"
cask "spotify"

mas "Slack", id: 803453959
mas "Spark", id: 1176895641

