tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "zsh"
brew "tmux"
brew "git"
brew "tig"
brew "ghq"
brew "vim"
brew "fasd"
brew "fzf"
brew "anyenv"
brew "direnv"
brew "reattach-to-user-namespace"
brew "tmux-mem-cpu-load"
brew "coreutils"
brew "mysql-client"
brew "jq"
brew "jid"
brew "gron"
brew "tree"
brew "ctop"
brew "beeftornado/rmtree/brew-rmtree"
brew "lesspipe"
brew "highlight"
brew "source-highlight"
brew "gh"
brew "fd"
brew "sd"
brew "exa"
brew "bat"
brew "dust"
brew "tldr"
brew "procs"
brew "ripgrep"
brew "bandwhich"
brew "cjbassi/ytop"
brew "translate-shell"
brew "mackup"
brew "awscli"
brew "aws/tap/aws-sam-cli"
brew "fabianishere/personal/pam_reattach"
brew "gradle-completion"
brew "mycli"
brew "pipx"

cask "font-hackgen"
cask "font-hackgen-nerd"

cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "session-manager-plugin"
cask "iterm2"
cask "docker"
cask "visual-studio-code"

cask "appcleaner"
cask "google-chrome"
cask "google-japanese-ime"
cask "authy"
cask "bitwarden"
cask "biscuit"
cask "dropbox"
cask "tableplus"
cask "postman"

cask "monitorcontrol"
cask "keyboardcleantool"
cask "alfred"
cask "bettertouchtool"
cask "karabiner-elements"
cask "showyedge"
cask "fuwari"
cask "bartender"

mas "Slack", id: 803453959
mas "Spark", id: 1176895641

